version: '3.7'

services:
  front:
    container_name: front
    build:
      context: ../100files/
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  back:
    container_name: back
    build:
      context: ../100filesback/
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
