- hosts: core
  become: true  
  roles:
    - role: git
      vars:
        FRONT: 100files
        CORE: 100filesback
        BASE_URL_FRONT: https://github.com/JuanDavidBallesteros/100Files_front.git
        BASE_URL_BACK: https://github.com/JuanDavidBallesteros/100FilesBack.git
    - role: compose
  vars:
    ADMINUSER: adminUser
    WORKING_DIR_BASE: /apps
  