---
## Update repositories
- name: Clone a repo with separate git directory
  git:
    repo: "{{ item.url }}" 
    dest: "{{ item.path }}"
    version: "{{ item.branch }}"
    force: yes
  loop:
    - { url: "{{ BASE_URL_FRONT }}", branch: "main", path: "{{ WORKING_DIR_BASE }}/{{ FRONT }}" }
    - { url: "{{ BASE_URL_BACK }}", branch: "main", path: "{{ WORKING_DIR_BASE }}/{{ CORE }}" }

- name: Tear down existing services
  docker_compose:
    files:
    - "{{ WORKING_DIR_BASE }}/orchestation/docker-compose.yml"
    project_src: "{{ WORKING_DIR_BASE }}/orchestation/docker-compose.yml"
    state: absent

- name: Create and start services
  docker_compose:
    files:
    - "{{ WORKING_DIR_BASE }}/orchestation/docker-compose.yml"
    project_src: "{{ WORKING_DIR_BASE }}/orchestation/docker-compose.yml"

- name: Run `docker-compose up` again
  docker_compose:
    files:
    - "{{ WORKING_DIR_BASE }}/orchestation/docker-compose.yml"
    project_src: docker-compose.yml
    build: no